version: '2.4'
services:
  pg:
    image: postgres:13.1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: billing
    ports:
      - "5432:5432"
  pg-init:
    image: postgres:13.1
    volumes:
      - ./docker/pg:/init
    entrypoint: /bin/bash
    command: /init/init.sh