spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/billing?sslmode=disable
    username: postgres
    password: ""
    pool:
      max-size: 10

management.endpoints.web.exposure.include: prometheus

logging.level:
  io.r2dbc.postgresql.client.ReactorNettyClient: error
