spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/billing?sslmode=disable
    username: postgres
    password: ""
    pool:
      max-size: 10

management.endpoints.web.exposure.include: prometheus